// src/lib/exportContent.js — build surveyor-ready documents from OpsHub data.
// HTML (→ Google Doc) for narrative reports; CSV (→ Google Sheet) for tables.
// Everything de-identified; these are the evidence artifacts a surveyor reads.

const esc = (s) => String(s ?? '').replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
const ms = (ts) => (ts?._seconds ? ts._seconds * 1000 : (ts?.toMillis ? ts.toMillis() : 0));
const fdate = (ts) => { const m = ms(ts); return m ? new Date(m).toLocaleDateString() : '—'; };
const fdt = (ts) => { const m = ms(ts); return m ? new Date(m).toLocaleString() : '—'; };

function docShell(title, subtitle, bodyHtml) {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(title)}</title></head><body>
<h1>${esc(title)}</h1>
${subtitle ? `<p><em>${esc(subtitle)}</em></p>` : ''}
${bodyHtml}
<hr><p><small>Generated by OpsHub · ${new Date().toLocaleString()}</small></p>
</body></html>`;
}

const csvCell = (s) => `"${String(s ?? '').replace(/"/g, '""')}"`;
const csvRow = (arr) => arr.map(csvCell).join(',');

// ---------- QI Study → Doc ----------
export function qiStudyDoc(study, points, actions, analyses) {
  const m = study.measure || {};
  const sorted = [...points].sort((a, b) => (a.period || '').localeCompare(b.period || ''));
  const body = `
<h2>Aim</h2><p>${esc(study.aim)}</p>
<h2>Measure</h2>
<p><strong>${esc(m.name || '—')}</strong> (${esc(m.unit || '')}) · Goal: ${esc(m.goal)} (${esc(m.direction)})</p>
<p>Population: ${esc(study.population || '—')} · Category: ${esc(study.category)}</p>
${study.baseline ? `<p><strong>Baseline:</strong> ${esc(study.baseline.value)}${esc(m.unit || '')} (${esc(study.baseline.period)})</p>` : ''}
<h2>Data</h2>
<table border="1" cellpadding="6" cellspacing="0"><tr><th>Period</th><th>Value</th><th>Numerator</th><th>Denominator</th><th>Note</th></tr>
${sorted.map((p) => `<tr><td>${esc(p.period)}</td><td>${esc(p.value)}${esc(m.unit || '')}</td><td>${esc(p.numerator ?? '')}</td><td>${esc(p.denominator ?? '')}</td><td>${esc(p.note || '')}</td></tr>`).join('')}
</table>
<h2>Interventions</h2>
${actions.length ? `<ul>${actions.map((a) => `<li>${esc(a.description)} — <strong>${esc(a.status)}</strong>${a.result ? ` (${esc(a.result)})` : ''}</li>`).join('')}</ul>` : '<p>None.</p>'}
<h2>Analysis</h2>
${[...analyses].sort((a, b) => ms(a.authoredAt) - ms(b.authoredAt)).map((an) => `<p><strong>${esc(an.phase)}:</strong> ${esc(an.narrative)}</p>`).join('') || '<p>None.</p>'}
${study.status === 'closed' ? `<h2>Conclusion</h2><p><strong>Outcome: ${esc(study.outcome)}</strong></p><p>${esc(study.conclusion)}</p>` : '<p><em>Study in progress.</em></p>'}`;
  return docShell(`QI Study: ${study.title}`, `Status: ${study.status}`, body);
}

// ---------- QI data points → Sheet ----------
export function qiStudyCsv(study, points) {
  const m = study.measure || {};
  const sorted = [...points].sort((a, b) => (a.period || '').localeCompare(b.period || ''));
  const rows = [
    csvRow(['Study', study.title]),
    csvRow(['Measure', `${m.name || ''} (${m.unit || ''})`]),
    csvRow(['Goal', `${m.goal ?? ''} (${m.direction || ''})`]),
    '',
    csvRow(['Period', 'Value', 'Numerator', 'Denominator', 'Source', 'Note']),
    ...sorted.map((p) => csvRow([p.period, p.value, p.numerator ?? '', p.denominator ?? '', p.source || 'manual', p.note || ''])),
  ];
  return rows.join('\r\n');
}

// ---------- Meeting minutes → Doc ----------
export function minutesDoc(committee, meeting) {
  const snap = meeting.templateSnapshot?.sections || [];
  const att = meeting.attendance || [];
  const body = `
<p><strong>${esc(committee.name)}</strong> — ${fdt(meeting.date)}${meeting.location ? ` · ${esc(meeting.location)}` : ''}</p>
<h2>Attendance</h2>
<table border="1" cellpadding="6" cellspacing="0"><tr><th>Member</th><th>Status</th></tr>
${att.map((a) => `<tr><td>${esc(a.name)}</td><td>${esc(a.status)}</td></tr>`).join('')}</table>
<p>Quorum: <strong>${meeting.quorumMet ? 'met' : 'not met'}</strong></p>
${snap.map((s) => {
    const c = meeting.sections?.[s.key];
    let content = '';
    if (s.type === 'text' || s.type === 'priorMinutes' || s.type === 'vote' || s.type === 'checklist') content = `<p>${esc(c?.text || '—')}</p>`;
    else if (s.type === 'qiReview') content = `<p>Studies reviewed: ${(meeting.reviewedStudyIds || []).length}</p>`;
    else if (s.type === 'actionItems') content = `<ul>${(meeting.actionItems || []).map((ai) => `<li>${esc(ai.description)}</li>`).join('') || '<li>None</li>'}</ul>`;
    else if (s.type === 'attendance') content = '<p><em>(see attendance above)</em></p>';
    return `<h2>${esc(s.title)}</h2>${content}`;
  }).join('')}`;
  return docShell(`Minutes: ${committee.name}`, fdate(meeting.date), body);
}

// ---------- Incident → Doc ----------
export function incidentDoc(inc, actions) {
  const inv = inc.investigation;
  const body = `
<p><strong>${esc(inc.refNumber)}</strong> · ${esc(inc.type)} · Severity: ${esc(inc.severity)} · ${esc(inc.location || '')}</p>
<p>Occurred: ${fdt(inc.occurredAt)} · Reported: ${fdt(inc.reportedAt)}</p>
<h2>What happened</h2><p>${esc(inc.description)}</p>
<h2>Investigation</h2>
${inv ? `<p><strong>Findings:</strong> ${esc(inv.findings)}</p><p><strong>Root cause:</strong> ${esc(inv.rootCause)}</p>${(inv.contributingFactors || []).length ? `<p><strong>Contributing factors:</strong> ${esc(inv.contributingFactors.join(', '))}</p>` : ''}` : '<p>Not investigated.</p>'}
<h2>Corrective / preventive actions</h2>
${actions.length ? `<ul>${actions.map((a) => `<li>[${esc(a.type)}] ${esc(a.description)} — <strong>${esc(a.status)}</strong>${a.result ? ` (${esc(a.result)})` : ''}</li>`).join('')}</ul>` : '<p>None.</p>'}
${inc.status === 'closed' ? `<h2>Resolution</h2><p>${esc(inc.outcome)}</p>` : '<p><em>Open.</em></p>'}`;
  return docShell(`Incident Report ${inc.refNumber}`, inc.title, body);
}
